# Generated by Django 3.2.9 on 2021-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functioninputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('m', models.IntegerField()),
                ('P', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
